Fix showstopper bug
```options.list``` is undefined. Causes server to crash. Removing the ```.list``` part seems to fix the problem.

/var/www/bogprisbot/node_modules/big-xml-streamer/lib/big-xml.js:14
  options.lists = options.lists || [];
                         ^

TypeError: Cannot read property 'lists' of undefined
    at new BigXmlReader (/var/www/bogprisbot/node_modules/big-xml-streamer/lib/big-xml.js:14:26)
    at Object.exports.createReader (/var/www/bogprisbot/node_modules/big-xml-streamer/lib/big-xml.js:8:10)